name: art_pen
version: 1.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: DArt Pen is a version of the Logo language. dartling is a domain model framework.
homepage: http://ondart.me/
documentation: http://goo.gl/OvQWwN
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'
    version: '>=2.0.0 <3.0.0'
  dartling_default_app:
    git: 'https://github.com/dzenanr/dartling_default_app.git'
    version: '>=1.0.5 <2.0.0'
